(ns catan-board.scenarios.fog-islands-3p
  "Fog Islands 3-Player scenario configuration for Catan: Seafarers.
   This scenario features two island clusters separated by water and fog hexes,
   with reveal mechanics for fog-covered terrain.

   Coordinates have been manually edited to match the reference image layout."
  (:require [catan-board.utils.hex :as hex]))

(def fog-islands-3p-scenario
  "Complete configuration for the Fog Islands 3-Player scenario.

   Layout:
   - Northwest island: 7 face-up terrain hexes (left side of board)
   - Southeast island: 7 face-up terrain hexes (right side of board)
   - 12 fog hexes: positioned between islands and around edges
   - 18 water hexes: outer border surrounding all hexes"
  {:id           :fog-islands-3p
   :name         "Fog Islands (3-player)"
   :player-count 3

   ;; Grid pattern: 5-6-7-8-7-6-5 columns = 44 total hexes
   :grid-pattern "5-6-7-8-7-6-5"

   ;; Hex coordinate sets by type
   ;; Coordinates are assigned to match the column-based grid generation
   ;;
   ;; All 44 coordinates generated by pattern "5-6-7-8-7-6-5":
   ;; q=-3 (5 hexes): [-3 -1] [-3 0] [-3 1] [-3 2] [-3 3]
   ;; q=-2 (6 hexes): [-2 -2] [-2 -1] [-2 0] [-2 1] [-2 2] [-2 3]
   ;; q=-1 (7 hexes): [-1 -3] [-1 -2] [-1 -1] [-1 0] [-1 1] [-1 2] [-1 3]
   ;; q=0  (8 hexes): [0 -4] [0 -3] [0 -2] [0 -1] [0 0] [0 1] [0 2] [0 3]
   ;; q=1  (7 hexes): [1 -4] [1 -3] [1 -2] [1 -1] [1 0] [1 1] [1 2]
   ;; q=2  (6 hexes): [2 -4] [2 -3] [2 -2] [2 -1] [2 0] [2 1]
   ;; q=3  (5 hexes): [3 -4] [3 -3] [3 -2] [3 -1] [3 0]
   :hex-types
   {;; Outer border water hexes (18 total)
    :water #{[-3 -1] [-2 -2] [-1 -3] [0 -4] [1 -4] [1 -3] [1 -2] [0 -1] [ -1 0] [-2 1] [-3 1]
             [0 3] [-1 3] [-1 2] [-0 1] [1 0] [2 -1] [3 -2]
             }

    ;; Fog hexes between and around islands (12 total)
    :fog #{;; cluster on the left
           [-2 3] [-3 3] [-3 2]

           ;; water through the middle
           [-2 2] [-1 1] [0 0] [1 -1] [2 -2]

           ;; cluster on the right
           [3 -3] [3 -4] [2 -3] [2 -4]}

    :terrain #{;; Face-up terrain hexes on two islands (14 total)
               ;; Northwest island cluster (7 hexes) - left side
               [-3 1] [-3 2]
               [-2 0] [-2 1]
               [-1 -1] [-1 0] [-1 1]

               ;; Southeast island cluster (7 hexes) - right side
               [0 -2] [0 -1] [0 0] [0 1]
               [1 -2] [1 -1] [1 0]}}

   ;; Resource and number distribution for face-up terrain hexes
   :face-up-distribution
   {:resources     {:wood   3
                    :brick  2
                    :sheep  3
                    :wheat  3
                    :ore    2
                    :desert 1}
    ;; Number tokens for non-desert hexes (14 terrain, 1 desert, so 13 tokens)
    :number-tokens {2  0
                    3  1
                    4  1
                    5  2
                    6  2
                    8  2
                    9  2
                    10 1
                    11 2
                    12 1}
    :assignment    :random}

   ;; Resource and number distribution for fog hexes
   ;; Includes new :gold resource type unique to Seafarers scenarios
   :fog-distribution
   {:resources     {:wood  1
                    :brick 2
                    :sheep 1
                    :wheat 2
                    :ore   2
                    :water 2
                    :gold  2}
    ;; Number tokens for non-desert fog hexes (12 fog, 2 desert, so 10 tokens)
    :number-tokens {2  0
                    3  2
                    4  1
                    5  1
                    6  1
                    8  1
                    9  1
                    10 1
                    11 1
                    12 1}
    :assignment    :on-reveal}

   ;; Harbor positions (8 total)
   ;; Each harbor: {:land-hex [q r] :direction int :type keyword}
   ;; Direction: 0=N, 1=NE, 2=SE, 3=S, 4=SW, 5=NW
   ;; Type: :generic (3:1) or resource-specific (2:1)
   ;; Positioned around the perimeter of the two island clusters
   :harbors
   [;; Northwest island harbors

    {:land-hex  [-3 0]
     :direction hex/DIRECTION_N
     :type      :generic}

    {:land-hex  [-1 -2]
     :direction hex/DIRECTION_NW
     :type      :wood}

    {:land-hex  [0 -3]
     :direction hex/DIRECTION_NW
     :type      :ore}

    {:land-hex  [-2 0]
     :direction hex/DIRECTION_SW
     :type      :brick}

    ;; Southeast island harbors
    {:land-hex  [0 2]
     :direction hex/DIRECTION_S
     :type      :generic}

    {:land-hex  [1 2]
     :direction hex/DIRECTION_SE
     :type      :wheat}

    {:land-hex  [3 0]
     :direction hex/DIRECTION_S
     :type      :sheep}

    {:land-hex  [3 -1]
     :direction hex/DIRECTION_SE
     :type      :generic}]})
